INSERT INTO PRODUCTS VALUES(1,3,'Fresh Organic Tomatoes',0,NULL,5.9900000000000002132,NULL,1,50,'placeholder_1.svg','Locally grown organic tomatoes, perfect for cooking and salads. Rich in vitamins and minerals.','Active',2);
INSERT INTO PRODUCTS VALUES(2,3,'Sweet Red Apples',0,NULL,4.5,NULL,2,30,'placeholder_2.svg','Crisp and sweet red apples, great for snacking or baking. High in fiber and antioxidants.','Active',1);
INSERT INTO PRODUCTS VALUES(3,3,'Organic Basil Seeds',0,NULL,2.9900000000000002132,NULL,1,100,'placeholder_3.svg','Premium organic basil seeds for growing fresh herbs at home. Easy to germinate and grow.','Active',3);
INSERT INTO PRODUCTS VALUES(4,3,'AI Generated Apples',0,NULL,6.9900000000000002132,NULL,1,25,'placeholder_4.svg','Fresh apples created using AI category suggestion and image generation','Active',1);
INSERT INTO PRODUCTS VALUES(5,3,'Fresh Red Apples',0,NULL,4.5,NULL,2,100,'placeholder_5.svg','Crisp and sweet red apples, perfect for snacking and baking. High in fiber and antioxidants.','Active',1);
INSERT INTO PRODUCTS VALUES(6,3,'Organic Bananas',0,NULL,3.25,NULL,1,80,'placeholder_6.svg','Ripe organic bananas, rich in potassium and perfect for smoothies or eating fresh.','Active',1);
INSERT INTO PRODUCTS VALUES(7,3,'Sweet Oranges',0,NULL,5.9900000000000002132,NULL,3,60,'placeholder_7.svg','Juicy sweet oranges packed with vitamin C. Great for fresh juice or eating.','Active',1);
INSERT INTO PRODUCTS VALUES(8,3,'Fresh Mangoes',0,NULL,8.75,NULL,2,45,'placeholder_8.svg','Premium tropical mangoes, sweet and juicy. Perfect for desserts and smoothies.','Active',1);
INSERT INTO PRODUCTS VALUES(9,3,'Strawberries',0,NULL,6.5,NULL,1,35,'placeholder_9.svg','Fresh local strawberries, sweet and perfect for desserts or eating fresh.','Active',1);
INSERT INTO PRODUCTS VALUES(10,3,'Fresh Tomatoes',0,NULL,4.25,NULL,2,120,'placeholder_10.svg','Vine-ripened tomatoes, perfect for cooking and salads. Rich in lycopene.','Active',2);
INSERT INTO PRODUCTS VALUES(11,3,'Organic Carrots',0,NULL,3.75,NULL,1,90,'placeholder_11.svg','Crunchy organic carrots, high in beta-carotene and perfect for cooking or snacking.','Active',2);
INSERT INTO PRODUCTS VALUES(12,3,'Green Lettuce',0,NULL,2.9900000000000002132,NULL,1,75,'placeholder_12.svg','Fresh green lettuce, crisp and perfect for salads and sandwiches.','Active',2);
INSERT INTO PRODUCTS VALUES(13,3,'Bell Peppers Mix',0,NULL,5.5,NULL,2,55,'placeholder_13.svg','Colorful mix of red, yellow, and green bell peppers. Great for cooking and salads.','Active',2);
INSERT INTO PRODUCTS VALUES(14,3,'Fresh Broccoli',0,NULL,4.75,NULL,1,40,'placeholder_14.svg','Fresh broccoli crowns, rich in vitamins and minerals. Perfect for steaming or stir-fry.','Active',2);
INSERT INTO PRODUCTS VALUES(15,3,'Organic Spinach',0,NULL,3.5,NULL,1,65,'placeholder_15.svg','Fresh organic spinach leaves, perfect for salads, smoothies, and cooking.','Active',2);
INSERT INTO PRODUCTS VALUES(16,3,'Sunflower Seeds',0,NULL,7.25,NULL,1,200,'placeholder_16.svg','Premium sunflower seeds for planting or snacking. High in healthy fats and protein.','Active',3);
INSERT INTO PRODUCTS VALUES(17,3,'Pumpkin Seeds',0,NULL,8.9900000000000002132,NULL,1,150,'placeholder_17.svg','Organic pumpkin seeds for growing giant pumpkins or healthy snacking.','Active',3);
INSERT INTO PRODUCTS VALUES(18,3,'Herb Seed Mix',0,NULL,12.5,NULL,1,100,'placeholder_18.svg','Mixed herb seeds including basil, oregano, thyme, and parsley for your herb garden.','Active',3);
INSERT INTO PRODUCTS VALUES(19,3,'Organic Turmeric Powder',0,NULL,9.75,NULL,1,80,'placeholder_19.svg','Premium organic turmeric powder, known for its anti-inflammatory properties.','Active',4);
INSERT INTO PRODUCTS VALUES(20,3,'Black Pepper Whole',0,NULL,11.25,NULL,1,95,'placeholder_20.svg','Whole black peppercorns, freshly dried for maximum flavor and aroma.','Active',4);
INSERT INTO PRODUCTS VALUES(21,3,'Cinnamon Sticks',0,NULL,8.5,NULL,1,70,'placeholder_21.svg','Premium Ceylon cinnamon sticks, perfect for baking and cooking.','Active',4);
INSERT INTO PRODUCTS VALUES(22,3,'AI Generated Product Test',0,NULL,25.989999999999998437,NULL,1,1,'default.jpg','Test product with AI features','Active',1);
